config/routes.rb
Rails.application.routes.draw do
 root 'top#main'
 get 'top/main'
 resources :products
 resources :cart_items, only: [:new,:create, :destroy]
 resources :carts, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items, dependent: :destroy
end

app/models/cartitem.rb
class Cartitem < ApplicationRecord
     belongs_to :cart
     belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
     has_one :cart_item, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
    def current_cart
        logger.debug(session[:cart_id])
        if session[:cart_id]
            cart = Cart.find(session[:cart_id])
        else
            cart = Cart.create
            session[:cart_id] = cart.id
        end
        cart
    end
    helper_method :current_cart
end

app/controllers/cartitems_controller.rb
class CartitemsController < ApplicationController
  def new
    @product_id = params[:product_id] 
  end
  
  def create
    logger.debug "-----------"
    c = CartItem.new(product_id: params[:product_id], cart_id: current_cart.id, qty: params[:qty])
    c.save
    logger.debug c.errors.full_messages
    redirect_to cart_path(current_cart.id)
  end

  def destroy
    cartitem = CartItem.find(params[:id])
    cartitem.destroy
    redirect_to cart_path(current_cart.id)
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = Cart.find(current_cart.id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(name: params[:product][:name], price: params[:product][:price])
    @product.save
    redirect_to products_path
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end
end

  

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
      redirect_to products_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartitems_helper.rb
module CartitemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cartitems/new.html.erb
<%= form_tag cart_items_path, method: :post do %>
  <%= hidden_field_tag :product_id, @product_id %>
  <p>
      <%= '商品名' %>
      <%= Product.find(@product_id).name %>
  </p>
  <p>
      <%= '価格' %>
      <%= Product.find(@product_id).price %>
  </p>
  <p>
      <%= label_tag :qty, '数量' %>
      <%= text_field_tag :qty, 1 %>
  </p>
  <p>
      <%= submit_tag '登録' %>
  </p>
<% end %>  

app/views/carts/show.html.erb
<% total = 0 %>
<% @cart.cartitems.each do |e| %>
    <p>
        <% p = Product.find(e.product_id) %>
        <%= p.name %>
        <%= p.price %>円
        <%= e.qty %>
        <%= link_to '消去', cartitem_path(e), method: :delete %>
        <% total += p.price.to_i * e.qty.to_i %>
    </p>
<% end %>

<p>
合計金額：<%= total %>円 
</p>

<p>
<%= link_to '商品一覧', products_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai7</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<% @products.each do |e| %>
    <p>
        <%=e.name%>
        <%=e.price%>円
        <%= link_to 'カートへ', new_cart_item_path(product_id: e.id) %>
        <%= link_to 'カートから外す', product_path(e), method: :delete %>
    </p>
<% end %>

<p>
<%= link_to 'カートを見る', cart_path(current_cart.id) %>
</p>
<hr>
<p>
<%= link_to '商品登録', new_product_path %>
</p>

app/views/products/new.html.erb
<%= form_for @product, url: {action: :create} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <%= f.submit '登録' %>
<% end %>

app/views/top/main.html.erb
<h1>Top#main</h1>
<p>Find me in app/views/top/main.html.erb</p>